In [1]:
import numpy as np

In [2]:
# 0차원 텐서

d=np.array(5)
print(d.ndim) # 차원수 출력
print(d.shape) # 텐서의 크기 출력 

0
()


In [3]:
# 1차원 텐서

d=np.array([1, 2, 3, 4])
print(d.ndim)
print(d.shape)

1
(4,)


In [4]:
# 2차원 텐서

d=np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(d.ndim)
print(d.shape)

2
(3, 4)


In [5]:
# 3차원 텐서

d=np.array([
            [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [10, 11, 12, 13, 14]],
            [[15, 16, 17, 18, 19], [19, 20, 21, 22, 23], [23, 24, 25, 26, 27]]
            ])
print(d.ndim)
print(d.shape)

3
(2, 3, 5)


In [6]:
a = np.array([8, 4, 5])
b = np.array([1, 2, 3])
print(a+b)
print(a-b)

[9 6 8]
[7 2 2]


In [7]:
a = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
b = np.array([[5, 6, 7, 8],[1, 2, 3, 4]])
print(a+b)
print(a-b)

[[15 26 37 48]
 [51 62 73 84]]
[[ 5 14 23 32]
 [49 58 67 76]]


In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a,b))

32


In [9]:
a = np.array([[1, 3],[2, 4]])
b = np.array([[5, 7],[6, 8]])
print(np.matmul(a,b))

[[23 31]
 [34 46]]
