In [8]:
import numpy as np
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [15]:
n_inputs = 3
n_neurons = 5

X0 = tf.placeholder(tf.float32, [None, n_inputs])
X1 = tf.placeholder(tf.float32, [None, n_inputs])

Wx = tf.Variable(tf.random_normal(shape=[n_inputs, n_neurons], dtype=tf.float32))
Wy = tf.Variable(tf.random_normal(shape=[n_neurons, n_neurons], dtype=tf.float32))
b = tf.Variable(tf.zeros([1, n_neurons]), dtype=tf.float32)


Y0 = tf.tanh(tf.matmul(X0, Wx) + b)
Y1 = tf.tanh(tf.matmul(Y0, Wy) + tf.matmul(X1, Wx) + b)

In [21]:
# t = 0
X0_batch = np.array([[0,1,2],
                    [3,4,5],
                    [6,7,8],
                    [9,0,1]])
# t = 1
X1_batch = np.array([[9,8,7],
                    [3,4,5],
                    [6,5,4],
                    [3,2,1]])

# Y0_val, Y1_val
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    Y0_val, Y1_val = sess.run([Y0, Y1], feed_dict={X0: X0_batch, X1: X1_batch})
    
print(Y0_val)
print(Y1_val)

[[ 0.9979179  -0.80881035 -0.72143656  0.993975   -0.13875717]
 [ 1.         -1.         -0.8413151   0.99995637  0.41715938]
 [ 1.         -1.         -0.9122346   0.9999998   0.773167  ]
 [-0.9576068  -1.          0.9999958   0.9672084   0.9929991 ]]
[[ 1.         -1.          0.39691892  0.9988248   0.6770818 ]
 [ 1.         -1.         -0.6859136   0.9996748  -0.14399116]
 [ 1.         -1.          0.53284186  0.6794064   0.82717156]
 [ 0.99689233 -0.999951   -0.9854381   0.8307894   0.8773768 ]]
