In [5]:
import tensorflow as tf
import numpy as np

In [47]:
X = []
Y = []
for i in range(6):
    seq = np.linspace(i * 0.1, (i + 4) * 0.1, 5)
    X_tmp = seq[:-1].tolist()
    y_tmp = seq[-1]
    X.append(X_tmp)
    Y.append(y_tmp)

X = np.array(X)
X = X.reshape(6,4,1)
Y = np.array(Y)
print(X)
print(Y)

[[[0. ]
  [0.1]
  [0.2]
  [0.3]]

 [[0.1]
  [0.2]
  [0.3]
  [0.4]]

 [[0.2]
  [0.3]
  [0.4]
  [0.5]]

 [[0.3]
  [0.4]
  [0.5]
  [0.6]]

 [[0.4]
  [0.5]
  [0.6]
  [0.7]]

 [[0.5]
  [0.6]
  [0.7]
  [0.8]]]
[0.4 0.5 0.6 0.7 0.8 0.9]


In [65]:
model = tf.keras.Sequential([
    tf.keras.layers.SimpleRNN(
        units=30,
        return_sequences=False,
        activation="tanh",
        input_shape=[4,1]
    ),
    tf.keras.layers.Dense(1)
])
model.compile(optimizer='adam', loss='mse')
history = model.fit(X, Y, epochs=400, verbose=0)

In [66]:
model.predict(X)

array([[0.38684613],
       [0.50234157],
       [0.6112838 ],
       [0.7118884 ],
       [0.8029833 ],
       [0.88399005]], dtype=float32)

In [67]:
X_test = np.array([[[0.8], [0.9], [1.0], [1.1]]])
print(model.predict(X_test))

[[1.0674945]]


In [68]:
model = tf.keras.Sequential([
    tf.keras.layers.LSTM(
        units=30,
        return_sequences=False,
        activation="tanh",
        input_shape=[4,1]
    ),
    tf.keras.layers.Dense(1)
])
model.compile(optimizer='adam', loss='mse')
history = model.fit(X, Y, epochs=400, verbose=0)

In [69]:
model.predict(X)

array([[0.40522113],
       [0.49938595],
       [0.59686494],
       [0.6970537 ],
       [0.7992971 ],
       [0.902912  ]], dtype=float32)