In [2]:
import numpy as np
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [3]:
n_steps = 2
n_inputs = 3
n_neurons = 5

X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])

basic_cell = tf.nn.rnn_cell.BasicRNNCell(num_units=n_neurons) 
outputs, states = tf.nn.dynamic_rnn(basic_cell, X, dtype=tf.float32)

X_batch = np.array([
    # t = 0   t = 1
    [[0,1,2],[9,8,7]],
    [[3,4,5],[3,4,5]],
    [[6,7,8],[6,5,4]],
    [[9,0,1],[3,2,1]]
])

with tf.Session() as sess:
    tf.global_variables_initializer().run()
    outputs_val = outputs.eval(feed_dict={X: X_batch})
    
print(outputs_val)

Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


/Users/formegusto/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/layers/legacy_rnn/rnn_cell_impl.py:427: UserWarning: `tf.nn.rnn_cell.BasicRNNCell` is deprecated and will be removed in a future version. This class is equivalent as `tf.keras.layers.SimpleRNNCell`, and will be replaced by that in Tensorflow 2.0.
  warnings.warn("`tf.nn.rnn_cell.BasicRNNCell` is deprecated and will be "
/Users/formegusto/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer_v1.py:1700: UserWarning: `layer.add_variable` is deprecated and will be removed in a future version. Please use `layer.add_weight` method instead.
  warnings.warn('`layer.add_variable` is deprecated and '


[[[ 0.638816   -0.56090176  0.15798484 -0.6124293  -0.15093209]
  [ 0.9988875  -0.84258145 -0.99998623  0.9463389  -0.7727719 ]]

 [[ 0.9832082  -0.82607335 -0.9611869  -0.25039104 -0.44821304]
  [ 0.9382712  -0.7426124  -0.7629273   0.33214357 -0.46803534]]

 [[ 0.99934953 -0.93751794 -0.9994306   0.19847013 -0.6711482 ]
  [ 0.97649634 -0.07314454 -0.9983443   0.98504984 -0.6095834 ]]

 [[-0.9017533   0.98894924 -0.9994994   0.99024445 -0.9989066 ]
  [ 0.9470609   0.56837237 -0.9898932   0.9605597   0.2947485 ]]]
